### ISSUE TITLE
Backend (almost) always returns status 500 on error.

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#200] opened 2023-03-31 14:07 UTC
## Steps to Reproduce the Problem

Provoke any error condition (E.g. by requesting a seed that does not exist).

## Expected Result

The backend should return an appropriate HTTP status code, such as 404 for elements that do not exist.

## Actual Result

With few exceptions, error 500 is returned because error handling has not yet been implemented.

**Comment by markus2330** [comment] 2023-03-31 14:21
Thank you for reporting! @kitzbergerg can you fix this please?

**Comment by kitzbergerg** [comment] 2023-04-01 10:17
I'll have a look after #172 and #180 are merged.

**Comment by markus2330** [comment] 2023-04-01 12:53
I don't agree with the prioritization. It is not nice to work with a backend that doesn't have proper error handling (which is even visible as you seemingly get wrong error codes). Furthermore, it easily can be that missing error handling affects the seed use case (and we would find user-visible problems, introducing extra effort to find the cause of the problems). Let us first get everything done needed for M1. Please at least have a look what the situation is.

**Comment by kitzbergerg** [comment] 2023-04-01 20:38
Ok. I just had a quick look. I'll create a PR soon.

Should we treat empty rows for example in find_all as a not_found error or just return an empty array? I personally prefer the second option (but I think currently we use the first one).

**Closed** 2023-04-02 15:49 UTC
Labels: bug, enhancement
