### ISSUE TITLE
Jenkins: PostGIS not available

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#411] opened 2023-06-02 19:30 UTC
My Jenkins jobs for #410 directly go into the failed state with an error stating, that the URL was not found.
Anyone having an idea what could cause this?

<img width="535" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/c62bd77e-7693-449d-9c26-0cfff625fa71">

**Comment by lukashartl** [comment] 2023-06-02 19:37
I think this is related to #386

/cc @fel115

**Comment by fel115** [comment] 2023-06-02 19:51
I can't reproduce the '404 Not Found' error. I only see a problem with the `diesel migration`command. 

`+ diesel migration run
Running migration 2023-01-20-024832_create_enums
Running migration 2023-01-21-024832_create_varieties
Running migration 2023-01-21-024920_create_seeds
Running migration 2023-02-04-132532_create_plant_detail
Running migration 2023-02-10-123415_rename_varieties
Running migration 2023-02-20-112009_alter_plant_detail
Running migration 2023-03-03-105611_remove_tags
Running migration 2023-03-03-140707_convert_variety_to_text
Running migration 2023-03-09-173153_make_plant_id_optional
Running migration 2023-03-29-111855_merge_plant_tables
Running migration 2023-04-12-162600_rename_plants_columns
Running migration 2023-04-12-162709_replace_varchars
Running migration 2023-04-12-162832_alter_plant_types
Running migration 2023-04-13-102425_new_plants_columns
Running migration 2023-04-14-113044_new_plants_reinsaat_columns
Running migration 2023-04-26-154153_map_creation
Running migration 2023-05-05-075334_map_versions
Running migration 2023-05-05-123527_map_owner
Running migration 2023-05-22-113625_unique_map_name
Running migration 2023-05-29-210302_additional_map_properties
Failed to run 2023-05-29-210302_additional_map_properties with: extension "postgis" is not available`

If I enter the URI, I don't get an 404 Error.

**Comment by ThorbenStaufer** [comment] 2023-06-02 20:13
Interesting that you don't see the 404.
But also the error message you get, it seems PostGIS is not installed on our production database.
Do you know who has access to that?

**Comment by fel115** [comment] 2023-06-02 20:49
By entering `https://build.libelektra.org/job/PermaPlanT-Folder/job/PermaplanT/job/345-additional-map-properties/3/display/redirect`, I get redirected to this `https://build.libelektra.org/blue/organizations/jenkins/PermaPlanT-Folder%2FPermaplanT/detail/345-additional-map-properties/3/pipeline` page. Is the 404 error still there? If so it could be something with the privileges.

I think @lukashartl has access to the db. 

Tomorrow I am going deeper in this bug.

**Comment by ThorbenStaufer** [comment] 2023-06-02 21:32
I'm not getting redirected, so I agree that it could have something to do with privileges.

**Comment by markus2330** [comment] 2023-06-03 04:29
I can reproduce, without login I get 404, when logged in it works.

As quick workaround we could create an account but better would be if we find a quick fix.

@fel115  Isn't the problem that the public permissions for this newly created folder "[PermaplanT-Folder](https://build.libelektra.org/job/PermaPlanT-Folder/)" are missing? When I try to go to this folder without login, I get a 404.

**Comment by lukashartl** [comment] 2023-06-03 05:22
> I can't reproduce the '404 Not Found' error. I only see a problem with the `diesel migration`command.
> 
> `+ diesel migration run Running migration 2023-01-20-024832_create_enums Running migration 2023-01-21-024832_create_varieties Running migration 2023-01-21-024920_create_seeds Running migration 2023-02-04-132532_create_plant_detail Running migration 2023-02-10-123415_rename_varieties Running migration 2023-02-20-112009_alter_plant_detail Running migration 2023-03-03-105611_remove_tags Running migration 2023-03-03-140707_convert_variety_to_text Running migration 2023-03-09-173153_make_plant_id_optional Running migration 2023-03-29-111855_merge_plant_tables Running migration 2023-04-12-162600_rename_plants_columns Running migration 2023-04-12-162709_replace_varchars Running migration 2023-04-12-162832_alter_plant_types Running migration 2023-04-13-102425_new_plants_columns Running migration 2023-04-14-113044_new_plants_reinsaat_columns Running migration 2023-04-26-154153_map_creation Running migration 2023-05-05-075334_map_versions Running migration 2023-05-05-123527_map_owner Running migration 2023-05-22-113625_unique_map_name Running migration 2023-05-29-210302_additional_map_properties Failed to run 2023-05-29-210302_additional_map_properties with: extension "postgis" is not available`

PostGIS should be enabled now 😄

**Comment by fel115** [comment] 2023-06-03 07:14
Now I adjusted the pattern of the item roles and the folder should have the same permissions as before.

**Comment by ThorbenStaufer** [comment] 2023-06-03 09:00
I can now see the Jenkins Pipeline again, so that worked.
But the job is still throwing an exception that postgis is not available.

**Comment by lukashartl** [comment] 2023-06-03 09:15
I've added the `CREATE EXTENSION` to the ci reset script.
Pipeline is running.

**Comment by lukashartl** [comment] 2023-06-03 09:20
ah, i see. the problem already occurs when building the schema inside docker, so it doesn't use the databases on our three servers.
I'll think of a fix...

**Comment by lukashartl** [comment] 2023-06-03 09:22
Ok, we should try the official `postgis` docker container, which is basically the vanilla `postgres` image with `postgis` enabled.

**Comment by markus2330** [comment] 2023-06-03 09:39
Please make sure the versions match exactly. PostGIS is quite picky.

**Comment by lukashartl** [comment] 2023-06-03 10:15
I tried to simply replace the docker image to the `postgis` image, but that didn't work:

```
Could not connect to database via `postgres://ci:ci@db/ci`: Invalid connection url for multiconnection
```

@kitzbergerg do I have to change the connection urls if I want to use postgis?

**Comment by kitzbergerg** [comment] 2023-06-03 10:19
> I tried to simply replace the docker image to the `postgis` image, but that didn't work:
> 
> ```
> Could not connect to database via `postgres://ci:ci@db/ci`: Invalid connection url for multiconnection
> ```
> 
> @kitzbergerg do I have to change the connection urls if I want to use postgis?

I have no idea. I have never used PostGIS and haven't set up our database. The only thing I can associated with multi connection as a discussion in diesel and the following https://docs.rs/diesel/latest/diesel/derive.MultiConnection.html. However this uses a newer version of diesel and I don't think this is related.

**Comment by markus2330** [comment] 2023-06-03 10:34
Please lets avoid wild guesses but try to replicate/narrow down based on facts. We already had the PostGIS extension in use several times, and up to now it worked with the connection URL we always used. It also works locally at least for Thorben (based on recent Nextcloud chats). @ThorbenStaufer is there any relevant change (e.g. in the connection URL) we should know about?

Other than that, it is always important in issues to give some context about error messages, e.g.:

- Is it the same PostGIS version? (depends on Docker image)
- Is it the same Diesel version? (Thorben PRs might have made changes there)
- etc.

**Comment by ThorbenStaufer** [comment] 2023-06-03 10:37
I haven't touched any connection URL or similar.

**Comment by lukashartl** [comment] 2023-06-03 11:08
I've created #413 for the docker image changes.
The branch is directly from master and I'll continue testing there.

**Comment by badnames** [comment] 2023-06-03 12:25
![image](https://github.com/ElektraInitiative/PermaplanT/assets/27735433/368284c2-fce8-4723-8c05-6f69507acc41)

Jenkins currently fails because the postgis extension already exists.
Changing "CREATE EXTENSION postgis;" to "CREATE EXTENSION IF NOT EXISTS postgis;" should fix it.

**Comment by lukashartl** [comment] 2023-06-03 12:48
thank you for pointing it out. should be fixed now 😄

**Comment by lukashartl** [comment] 2023-06-04 22:41
Here is what I found so far.

If I change the image from `postgres:alpine` to `postgis/postgis:13-3.1-alpine` (PostgreSQL 13, PostGIS 3.1; matches with Debian); the `schema.rs` becomes somewhat wrong: see #413 .

```
error: cannot find attribute `max_length` in this scope
   --> src/schema.rs:254:11
    |
254 |         #[max_length = 2048]
    |           ^^^^^^^^^^
```

If I do the changes on top of #410 , I get the following error:

```
Could not connect to database via `postgres://ci:ci@db/ci`: Invalid connection url for multiconnection
```

Maybe someone from the backend team can help with these issues, as they seem to have something to do with Rust/Diesel/etc.?

**Comment by lukashartl** [comment] 2023-06-10 09:19
Last time I checked building on master works and since PostGIS is also enabled now, I'll close this issue.

If you find other problems, feel free to create new issues :rocket:

**Closed by lukashartl** 2023-06-10 09:19 UTC
Labels: bug, CI
