### ISSUE TITLE
scrape reinsaat.at

### ISSUE THREAD

**Issue by markus2330** [ElektraInitiative/PermaplanT#123] opened 2023-03-19 11:02 UTC
e.g. https://www.reinsaat.at/shop/DE/gurken/rs-gu-01.22_nishiki/

- [x] Tausendkorngewicht
- [x] Artikelnummer
- [x] Dates (für Voranzucht, Aussaat, Freiland, Ernte,...)
- [x] Keimtemperatur 07a3b3c7d59b219e6c5ca53fcf045a598e99e0af
- [x] Pflanzabstände
- [x] Saatgutbedarf
- [x] Saattiefe

__*EDIT 09.04.2023:*__

- [x] both English and german versions
- [x] fetch Suitable for professional cultivation(tractor icon)
- [x] ~~fetch Winterernte(snowflake icon)~~ This indication was used only in their [catalog](https://www.reinsaat.at/fileadmin/Bibliothek/Allgemeine/REINSAAT_KATALOG_2023_web.pdf) but not on the webpage
- [ ] fetch binomial name
     - need assistance from @yvonnemarkl and @markus2330 on how to construct the binomial name given the custom namings on reinsaat

**Comment by markus2330** [comment] 2023-04-13 16:02
Information about unique name is here: #274

**Comment by aidnurs** [comment] 2023-04-14 11:12
I've updated the files in the Nextcloud with missing columns, the issue is fixed now

**Closed** 2023-04-14 11:13 UTC
