### ISSUE TITLE
deployed permaplant.net broken (react runtime issues)

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#504] opened 2023-06-23 14:33 UTC
## Steps to Reproduce the Problem

Trying to open the map editor seems to fail, due to some runtime error.
I created a new map in the Map Overview and tried to open the editor through clicking on the card in the list.
Same issue pops up when trying to navigate straight via URL with valid map id.

## Expected Result

Map editor with toolbar, canvas and Base/Plants Layer loaded should be visible on the screen.

## Actual Result

Instead, I get a blank main section and following error in the browser console:

<img width="394" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/1cb72182-69ac-4df3-8b02-7b1fc37f6aa5">

## System Information

- PermaplanT: master
- Operating System: Windows 11 
- Browser: Microsoft Edge (Chromium) 

I pulled and built master locally on my machine and I have no issues whatsoever.
I believe the problem could have been introduced in the pipeline.

**Comment by markus2330** [comment] 2023-06-23 14:39
@fel115 @lukashartl can you take a look?

**Comment by markus2330** [comment] 2023-06-24 12:54
I can confirm, I only see a blank page on `https://dev.permaplant.net/maps/1` and the Console says:

```
Content Security Policy: The page’s settings observed the loading of a resource at https://dev.permaplant.net/sw.js (“worker-src”). A CSP report is being sent. [registerSW.js:1:97](https://dev.permaplant.net/registerSW.js)
Uncaught (in promise) DOMException: The operation is insecure. [registerSW.js:1](https://dev.permaplant.net/registerSW.js)
TypeError: t.find is not a function
    Wv https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    iL https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    aL https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    ru https://dev.permaplant.net/assets/client.f39aa74a.js:30
    fi https://dev.permaplant.net/assets/client.f39aa74a.js:32
    uf https://dev.permaplant.net/assets/client.f39aa74a.js:32
    rf https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Gp https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Sl https://dev.permaplant.net/assets/client.f39aa74a.js:32
    xi https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Ms https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Rt https://dev.permaplant.net/assets/client.f39aa74a.js:30
    Se https://dev.permaplant.net/assets/client.f39aa74a.js:32
[client.f39aa74a.js:32:175](https://dev.permaplant.net/assets/client.f39aa74a.js)
Uncaught TypeError: t.find is not a function
    Wv https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    iL https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    aL https://dev.permaplant.net/assets/App.bd8ea89a.js:98
    ru https://dev.permaplant.net/assets/client.f39aa74a.js:30
    fi https://dev.permaplant.net/assets/client.f39aa74a.js:32
    uf https://dev.permaplant.net/assets/client.f39aa74a.js:32
    rf https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Gp https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Sl https://dev.permaplant.net/assets/client.f39aa74a.js:32
    xi https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Ms https://dev.permaplant.net/assets/client.f39aa74a.js:32
    Rt https://dev.permaplant.net/assets/client.f39aa74a.js:30
    Se https://dev.permaplant.net/assets/client.f39aa74a.js:32
```

**Comment by lukashartl** [comment] 2023-06-24 13:08
Can also reproduce the problem.

```
function Wv(t, e) {
    return t.find(n=>n.type_ === e && !n.is_alternative)
}
```

Seems like `t` does not provide the function `find`. But I can't really help you with the frontend code to be honest.

**Comment by ThorbenStaufer** [comment] 2023-06-30 13:52
I found the cause of the problem, but I honestly can't explain how it happened.
The function in question performes a find() on an array of layers to extract the default layer of a given layer type.
But somehow, this function gets called on a piece of HTML code, or to be precise, on the generated index.html file.

<img width="936" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/daa2065c-200d-48b7-a111-1389b21b0dc2">

How this happens completely escapes my reasoning.
@Bushuo since you wrote the code, do you know why this could happen?

**Comment by lukashartl** [comment] 2023-06-30 18:08
I think I know why:

* We are doing an AJAX call to `https://dev.permaplant.net/maps/api/maps/9/layers`
* This is not handled by the backend, because `/maps/api` is not a proxy route.
* So FallbackResource returns the index.html

`/maps/api/maps/9/layers` probably should be `/api/maps/9/layers` to be correctly routed.

**Comment by markus2330** [comment] 2023-07-02 07:53
Thanks for this excellent triage.

I am not sure if it is caused by the errors but on https://dev.permaplant.net/maps/11 I see now a blank page

The errors look like the one already posted/triaged by lukas:

```
Privacy Badger failed to set navigator.globalPrivacyControl, probably because another extension set it in an incompatible way first. [11:17:17](https://dev.permaplant.net/maps/11)
Failed to register/update a ServiceWorker for scope ‘https://dev.permaplant.net/’: Storage access is restricted in this context due to user settings or private browsing mode. [registerSW.js:1:97](https://dev.permaplant.net/registerSW.js)
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI. [registerSW.js:1:97](https://dev.permaplant.net/registerSW.js)
Content Security Policy: The page’s settings observed the loading of a resource at https://dev.permaplant.net/sw.js (“worker-src”). A CSP report is being sent. [registerSW.js:1:97](https://dev.permaplant.net/registerSW.js)
Uncaught (in promise) DOMException: The operation is insecure. [registerSW.js:1](https://dev.permaplant.net/registerSW.js)
TypeError: t.find is not a function
    j0 https://dev.permaplant.net/assets/App.7b24829f.js:98
    _A https://dev.permaplant.net/assets/App.7b24829f.js:98
    wA https://dev.permaplant.net/assets/App.7b24829f.js:98
    ru https://dev.permaplant.net/assets/client.cc89fa67.js:30
    fi https://dev.permaplant.net/assets/client.cc89fa67.js:32
    sf https://dev.permaplant.net/assets/client.cc89fa67.js:32
    lf https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Xp https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Sl https://dev.permaplant.net/assets/client.cc89fa67.js:32
    xi https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Fs https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Rt https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Se https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Se https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Ae https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Rc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Cc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    i https://dev.permaplant.net/assets/client.cc89fa67.js:9
    n https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    r https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    promise callback*Nu https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    l https://dev.permaplant.net/assets/client.cc89fa67.js:9
    dispatch https://dev.permaplant.net/assets/Root.790270d8.js:1
    setData https://dev.permaplant.net/assets/Root.790270d8.js:1
    onSuccess https://dev.permaplant.net/assets/Root.790270d8.js:1
    m https://dev.permaplant.net/assets/client.cc89fa67.js:9
    promise callback*g https://dev.permaplant.net/assets/client.cc89fa67.js:9
    Vm https://dev.permaplant.net/assets/client.cc89fa67.js:9
    fetch https://dev.permaplant.net/assets/Root.790270d8.js:1
    executeFetch https://dev.permaplant.net/assets/client.cc89fa67.js:9
    onSubscribe https://dev.permaplant.net/assets/client.cc89fa67.js:9
    subscribe https://dev.permaplant.net/assets/client.cc89fa67.js:9
    Ih https://dev.permaplant.net/assets/client.cc89fa67.js:40
    Cc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Ul https://dev.permaplant.net/assets/client.cc89fa67.js:32
    fn https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Jp https://dev.permaplant.net/assets/client.cc89fa67.js:32
    E https://dev.permaplant.net/assets/client.cc89fa67.js:17
    Z https://dev.permaplant.net/assets/client.cc89fa67.js:17
    EventHandlerNonNull* https://dev.permaplant.net/assets/client.cc89fa67.js:17
    <anonymous> https://dev.permaplant.net/assets/client.cc89fa67.js:17
[11:2367:25](https://dev.permaplant.net/maps/11)
Uncaught TypeError: t.find is not a function
    j0 https://dev.permaplant.net/assets/App.7b24829f.js:98
    _A https://dev.permaplant.net/assets/App.7b24829f.js:98
    wA https://dev.permaplant.net/assets/App.7b24829f.js:98
    ru https://dev.permaplant.net/assets/client.cc89fa67.js:30
    fi https://dev.permaplant.net/assets/client.cc89fa67.js:32
    sf https://dev.permaplant.net/assets/client.cc89fa67.js:32
    lf https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Xp https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Sl https://dev.permaplant.net/assets/client.cc89fa67.js:32
    xi https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Fs https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Rt https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Se https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Se https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Ae https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Rc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Cc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    i https://dev.permaplant.net/assets/client.cc89fa67.js:9
    n https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    r https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    promise callback*Nu https://dev.permaplant.net/assets/client.cc89fa67.js:9
    u https://dev.permaplant.net/assets/client.cc89fa67.js:9
    l https://dev.permaplant.net/assets/client.cc89fa67.js:9
    dispatch https://dev.permaplant.net/assets/Root.790270d8.js:1
    setData https://dev.permaplant.net/assets/Root.790270d8.js:1
    onSuccess https://dev.permaplant.net/assets/Root.790270d8.js:1
    m https://dev.permaplant.net/assets/client.cc89fa67.js:9
    promise callback*g https://dev.permaplant.net/assets/client.cc89fa67.js:9
    Vm https://dev.permaplant.net/assets/client.cc89fa67.js:9
    fetch https://dev.permaplant.net/assets/Root.790270d8.js:1
    executeFetch https://dev.permaplant.net/assets/client.cc89fa67.js:9
    onSubscribe https://dev.permaplant.net/assets/client.cc89fa67.js:9
    subscribe https://dev.permaplant.net/assets/client.cc89fa67.js:9
    Ih https://dev.permaplant.net/assets/client.cc89fa67.js:40
    Cc https://dev.permaplant.net/assets/client.cc89fa67.js:30
    Ul https://dev.permaplant.net/assets/client.cc89fa67.js:32
    fn https://dev.permaplant.net/assets/client.cc89fa67.js:32
    Jp https://dev.permaplant.net/assets/client.cc89fa67.js:32
    E https://dev.permaplant.net/assets/client.cc89fa67.js:17
    Z https://dev.permaplant.net/assets/client.cc89fa67.js:17
    EventHandlerNonNull* https://dev.permaplant.net/assets/client.cc89fa67.js:17
    <anonymous> https://dev.permaplant.net/assets/client.cc89fa67.js:17
[App.7b24829f.js:98:16380](https://dev.permaplant.net/assets/App.7b24829f.js)

​
```

**Comment by ThorbenStaufer** [comment] 2023-07-03 12:53
> We are doing an AJAX call to https://dev.permaplant.net/maps/api/maps/9/layers

I don't understand why. We use the exact same syntax as in every other API call and the URL looks fine when running it locally.

**Comment by markus2330** [comment] 2023-07-03 18:04
@4ydan this is one of the most important PermaplanT's issues. Maybe you can take a look if you somehow have an idea how to fix it?

**Comment by 4ydan** [comment] 2023-07-03 18:06
Looking

**Comment by markus2330** [comment] 2023-07-03 18:09
This affects https://www.permaplant.net/maps/1 and https://pr.permaplant.net/maps/1 too.

**Comment by 4ydan** [comment] 2023-07-03 19:39
It doesnt seem to be on master or https://pr.permaplant.net/maps/1, or is it just me? For me it works?
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/1be71753-4ed7-4247-b7fd-e03addcea8dc)
Or am I doing something wrong. Sorry

**Comment by ThorbenStaufer** [comment] 2023-07-03 19:41
Locally it runs perfectly. The error only occurs on the deployed builds.

**Comment by 4ydan** [comment] 2023-07-03 19:42
Oh I forgot that, yea you mentioned it, ok interesting, not easy to debug I guess

**Comment by lukashartl** [comment] 2023-07-03 19:47
It has to do with how the urls are built.

For all deployed instances

```
export VITE_BASE_API_URL=""
```

Maybe we should set it to `/`, so that URLs are build relative to the current Origin.

We did this a few months ago, so that we can use the Same deployed frontend code for all instances. If we would have added the concrete hostnames, we would need to compile three different frontend deployables.

**Comment by markus2330** [comment] 2023-07-04 04:34
According to https://vitejs.dev/config/shared-options.html#base NOT setting should do the trick as it would default to /. Setting it explicitly to / should work, too?

Anyway, VITE_BASE_API_URL is not documented at all, this should be fixed, too. At least in frontend/.env.sample something must be said about it.

**Comment by lukashartl** [comment] 2023-07-04 06:01
PR:

* #569

**Comment by Bushuo** [comment] 2023-07-04 06:18
@markus2330 The documentation that you found is for something different. VITE_BASE_API_URL is a custom environment variable used by our http client as the base URL for the api endpoints.
Lukas fix should work though.

**Comment by ThorbenStaufer** [comment] 2023-07-04 07:50
May have worked not that well:

<img width="210" alt="image" src="https://github.com/ElektraInitiative/PermaplanT/assets/101188734/c79444bd-1a1a-4c26-a208-6cc85e418f11">

**Comment by lukashartl** [comment] 2023-07-08 19:05
I am currently doing a video conference with @4ydan and we are discussing this issue.

# Building URLs during Development

When you are running Frontend+Backend on your machine (all developers),
then you are basically spawning two servers (each with it's own origin):

* `http://localhost:5173` serving ONLY the frontend
* `http://localhost:8080`

And the baseApiUrl is simply set to the full URL.

So all urls are built like this: `${baseApiUrl}/api/test`.

# Building URLs in Production

In "production" both are running under the same origin (e.g. www.permaplant.net serving BOTH frontend and backend). Backend requests (e.g. `/api/*`) are proxied to the backend instance, frontend requests are handled by httpd directly.

In production we want the URLs to be concatenated directly with the origin (hence using `/` as our Base API Url). We are doing this since the beginning. Nothing has changed since then.

Now it seems like there are multiple ways we are using to build the request URLs.

Because if the browser encounters an url like this `/api/map`, it knows that this URL is relative to the current window.location.origin.

Currently there are two ways to build the URL in the code:

## Number 1

https://github.com/ElektraInitiative/PermaplanT/blob/6bd3a547ac873a81b93a365e17a59b25753b96b1/frontend/src/features/map_planning/routes/MapWrapper.tsx#L118-L121

## Number 2

https://github.com/ElektraInitiative/PermaplanT/blob/6bd3a547ac873a81b93a365e17a59b25753b96b1/frontend/src/features/map_planning/layers/plant/api/getSeasonalAvailablePlants.ts#L21-L23

https://github.com/ElektraInitiative/PermaplanT/blob/6bd3a547ac873a81b93a365e17a59b25753b96b1/frontend/src/config/axios/index.ts#L10-L18

## Explanation

Before #569 it was set to the empty string.
This works great with number 1 (because it gets rendered as `/api/updates/maps`), but bad with number 2, because it gets rendered as `/maps/api/maps/...`. (`/maps/` in the beginning is wrong)

Easy fix would be:

```diff
-   `api/maps/${mapId}/layers/plants/suggestions?${searchParams.toString()}`,
+   `/api/maps/${mapId}/layers/plants/suggestions?${searchParams.toString()}`,
```

With #569: BASE_API_URL set to `/` (which means relative to the current origin), it now gets concatenated to `//api/updates/maps` and the browser renders a wrong url, due to the TWO slashes.

If it would get rendered to `/api/updates/maps` (only one slash at the beginning), it would prepend the current `window.location.origin` and it would work.

# How we should continue

We shouldn't mix the way URLs are built.

**Comment by lukashartl** [comment] 2023-07-09 10:15
#590 seems to fix the issue.

Can someone please double check 😀
Maps seem to load, but I am only on mobile, so I cannot reliable test it.

**Comment by lukashartl** [comment] 2023-07-09 19:35
#590 did the job :rocket:

https://dev.permaplant.net works for me ❤️

**Closed by lukashartl** 2023-07-09 19:35 UTC
Labels: bug, help wanted, urgent

**Comment by markus2330** [comment] 2023-07-11 06:28
Really great job done here!

@ThorbenStaufer thanks for the report :eye: :heart: 

@lukashartl thanks for triage and fix :1st_place_medal:
