### ISSUE TITLE
`ModalOverlay` of Guided Tour disappears after canceling skip

### ISSUE THREAD

**Issue by ThorbenStaufer** [ElektraInitiative/PermaplanT#752] opened 2023-07-30 22:58 UTC
### Steps to Reproduce the Problem

- open the map editor
- cancel the tour via the X
- cancel the modal popup

### Expected Result

Previous tour step is shown with modal overlay, i.e. the background darkens and is not clickable.

### Actual Result

Previous tour step is show, but without modal overlay, i.e. the background is normal and clickable

### PermaplanT version

738-allow-continue-tour

### Operating System

Windows

### Browser

Microsoft Edge

**Comment by markus2330** [comment] 2023-07-31 05:57
I can reproduce with Firefox. The problem is a bit worse than I thought: When I click somewhere, it counts like a confirmation. At least this should be fixed for the release tomorrow but better is to fix this fully.

**Comment by ThorbenStaufer** [comment] 2023-07-31 07:36
Will be fixed with #753.

**Closed** 2023-07-31 16:53 UTC
Labels: bug
