### ISSUE TITLE
useInitializeMap called intensively

### ISSUE THREAD

**Issue by absurd-turtle** [ElektraInitiative/PermaplanT#1075] opened 2023-11-20 10:59 UTC
While working on the default layer issue I noticed that useInitiliazeMap is called 10 times when loading a map.
This needs to be investigated.

**Comment by badnames** [comment] 2023-12-03 21:52
I have noticed similar patterns across the entire editor.
The base layerfor example is also called multiple times after a value it depends on has changed.

Although I could not find a specific cause, my guess is that main problem is that these components depends on a lot of frequently changing state.
The other reason might be that we use many independent requests to the backend  while initializing the map.
This is problematic because react re-renders each component that is affected by a state change.
Again, keep in mind that this is mainly speculation at this point!

However, if it turns out to be true we could try the following solutions:
- Reduce the amount of state BaseStage depends on (e.g. by spliting it up into sub-components)
- Implement more consolidated REST APIs that return the entire map state in fewer requests.
- Consider using [GraphQL](https://graphql.org/) or a similar library if the above solution becomes too much work in the long run.

**Comment by markus2330** [comment] 2023-12-10 17:19
@Bushuo when refactoring/improving API calls, the most important imho/afaics would be that we can reduce the number of calls (especially sequence of calls that could be grouped together).

But overall the most important non-functional requirement of PermaplanT is that we improve performance/memory. With realistic maps it is already getting slow, e.g. zooming #1089, even though we have only one filled layer. @badnames works on this via #1056 and @danielsteinkogler will check if maybe some Konva elements are more performant than others. Suggestions/ideas on that topic are very welcomed.

**Comment by Bushuo** [comment] 2023-12-10 21:21
@markus2330 
What do you mean by sequence of calls? Calling the API concurrently, instead of sequentially, to reduce load times if the calls are independent from one another? I thing we are already doing this. This is by default with react query.

What could be an improvement over the current way of doing things is using the data API of react router.
I don't know why we chose not to use it, because that happenend before I joined the team last march but react-router supports a data api that defines all the data that should be available to a route on navigation.
https://reactrouter.com/en/main/route/loader

**Comment by Bushuo** [comment] 2023-12-10 21:29
I think we should first figure out exactly why we have performance problems. Is it rerendering to often, etc. Then figure out a way to mitigate it.

**Comment by markus2330** [comment] 2023-12-11 12:10
> What do you mean by sequence of calls?

I mean that they have some data dependency, i.e., output from one API call is used as input to the next call etc. @badnames said that we already have such situations. According to our architecture, however, we should not have this. Every user action ideally should be only one API call.

>  I think we should first figure out exactly why we have performance problems.

I fully agree. It does not make sense to search for solutions as long as the problem is not clearly understood. Input on that topic is welcome.

Btw. performance when loading the map currently is not so bad. It is mostly when working on the map with many elements. So I'll close the issue for now with an indicator that it might be needed later.

**Closed by markus2330** 2023-12-11 12:10 UTC
Labels: needed later
