### ISSUE TITLE
Unit tests: fail on non-empty database

### ISSUE THREAD

**Issue by 4ydan** [ElektraInitiative/PermaplanT#589] opened 2023-07-06 22:10 UTC
### Describe the Bug

`test test::plant::test_get_all_plants_succeeds ... FAILED`

Seems to fail locally after resetting the db

### Steps to Reproduce the Problem

make reset-database
make test-backend

### Expected Result

All tests pass

### Actual Result

one test fails

### PermaplanT version

master

### Operating System

Windows 10 inside devcontainer

### Browser

-

### Versions of other relevant software/extensions

-

**Comment by ThorbenStaufer** [comment] 2023-07-07 19:16
I think I know what the problem is.

At least on the local build, the backend tests do not use their own test database, but instead use the main database and run the operations in a transaction that gets aborted at the end. It works in the sense, that test entities do not persist after the tests are finished, but production data can interfere with the assertions. 

In the case of this particular test, we add 2 test maps at the test startup and then query for all available maps. The assertions would be right, if only the test maps would be returned by the API, but instead we also get all the other maps in the database.
At least that is the cause for the failure when I run them on my local build.
 
Since it made no issues in Jenkins until now, I believed that the pipeline on the contrary does use its own test database. It is not visible on your screenshot, but it seems the test case for creating a map was handled before the search test case. Since all tests run in the same transaction, it could be that the search test case also picks up the map created by the create test case.

**Comment by 4ydan** [comment] 2023-07-07 20:07
Thank you very much for the detailed explanation. Would be nice if we could refactor this (and maybe other tests) to be more isolated and maybe have their own database if that is not too much action.

**Comment by markus2330** [comment] 2023-07-11 14:03
> make test-frontend

I think you mean `make test-backend` here?

@ThorbenStaufer thx for helping out here!

Shouldn't this easy to fix if the test cases use relative instead of absolute numbers? So run page.results.len() initially, add two items and check if it is 2 more?

**Comment by markus2330** [comment] 2023-07-11 14:04
If it is about names: let us use very obscure test names, so that it won't find maps that users might actually have.

@4ydan I wonder, doesn't the .devcontainer setup run the tests in isolation?

**Comment by 4ydan** [comment] 2023-07-11 14:40
Oh yea I meant test-backend

> @4ydan I wonder, doesn't the .devcontainer setup run the tests in isolation?

No, the devcontainer database has a mounted volume which is persistent after container restarts, so if the tests don't clean up, you can only run that test once successfully.

**Comment by 4ydan** [comment] 2023-09-18 12:49
There is now 5 tests in totally failing local for me. Can someone reproduce this?
![image](https://github.com/ElektraInitiative/PermaplanT/assets/53004139/51cafe93-871b-4be1-9e5c-fd6c0a2e82d0)

We should avoid adding tests that cant be executed locally.

**Comment by markus2330** [comment] 2023-09-18 16:50
For me also 5 tests failed:

```
test test::map::test_can_search_maps ... FAILED
test test::plant::test_get_all_plants_succeeds ... FAILED
test test::plantings::test_can_delete_planting ... FAILED
test test::plantings::test_can_search_plantings ... FAILED
test test::plantings::test_removed_planting_outside_loading_offset_is_not_in_timeline ... FAILED
```

I executed it with `make test-backend` (on master), shouldn't that make sure that migrations ran?

**Comment by 4ydan** [comment] 2023-09-18 17:51
> I executed it with make test-backend (on master), shouldn't that make sure that migrations ran?
`make test-backend` is just running the tests

**Comment by markus2330** [comment] 2023-09-19 06:07
Which tests failed for you?

I think we can close this issue by simply documenting that the tests require a clean database.

**Comment by 4ydan** [comment] 2023-09-23 11:42
> I think we can close this issue by simply documenting that the tests require a clean database.

I dont think all tests are passing with a clean database.
`test test::plant::test_get_all_plants_succeeds ... FAILED` for example doesnt work for me.

**Comment by markus2330** [comment] 2023-09-23 12:26
>  I dont think all tests are passing with a clean database.

How do they succeed on pr.permaplant.net then? There is a clean database, isn't there?

Can you split up the issue? Tests failing on clean database is critical and needs to be fixed.

**Comment by 4ydan** [comment] 2023-09-23 12:42
> How do they succeed on pr.permaplant.net then? There is a clean database, isn't there?

I have no idea

> Can you split up the issue?

This issue was about `test_can_search_maps` which seems to PASS, and is now about `test_get_all_plants_succeeds`

**Comment by 4ydan** [comment] 2023-09-23 12:49
Now all tests pass, hm, idk

**Closed** 2023-10-16 03:37 UTC
Labels: bug, wontfix, backend
