### ISSUE TITLE
Introduce map polygon.

### ISSUE THREAD

**Issue by badnames** [ElektraInitiative/PermaplanT#816] opened 2023-08-11 11:36 UTC
### Tasks

Users should be able to add a polygon outlining the maps borders.

### Use case

Base Layer, Heatmap

**Comment by markus2330** [comment] 2023-08-11 11:58
Thank you for creating the issue! To avoid round-trips, please say more specifically what you want to do. Where do you want to make a button to start the polygon, how will entering points of polygons work and how can you close the polygon?

**Comment by markus2330** [comment] 2023-11-06 05:47
Is this a duplicate of #349?

**Closed** 2023-11-27 09:33 UTC
Labels: duplicate, enhancement
